<!DOCTYPE html>
<html>
<head>
<title>Wed Jul 28, 2021 : #uscms (osg)</title>
</head>
<body>
<h3>Wed Jul 28, 2021 : #uscms (osg)</h3>
<span style="color: #a72f79"><span style="font-size: small">(12:32:53)</span> <b>andrew.melo:</b></span> on <a href="http://ce5-vanderbilt.sites.opensciencegrid.org">ce5-vanderbilt.sites.opensciencegrid.org</a>, we're consistently getting the following error: I have no idea of how to debug this, any hints?<br/><pre>012 (716981.0) 2021-07-28T17:07:27 JobHeldEvent<br/>HoldReasonCode:0<br/>HoldReason:Network error talking to schedd, probably an authorization failure<br/>HoldReasonSubCode:0</pre><br/>
<span style="color: #53b759"><span style="font-size: small">(14:56:27)</span> <b>eric.appelt:</b></span> We are also getting these timeout connection errors, not sure if related:<br/><pre>07/28/21 11:27:42 [2045738] Evaluating periodic job policy expressions.<br/>07/28/21 11:27:47 [2045738] in doContactSchedd()<br/>07/28/21 11:28:02 [2045738] condor_read(): timeout reading 21 bytes from schedd at &lt;129.59.197.77:25304&gt;.<br/>07/28/21 11:28:02 [2045738] IO: Failed to read packet header<br/>07/28/21 11:28:02 [2045738] SetEffectiveOwner(lcgadmin) failed with errno=110: Connection timed out.<br/>07/28/21 11:28:02 [2045738] Failed to connect to schedd! Will retry<br/>07/28/21 11:28:07 [2045738] in doContactSchedd()<br/>07/28/21 11:28:22 [2045738] condor_read(): timeout reading 21 bytes from schedd at &lt;129.59.197.77:25304&gt;.<br/>07/28/21 11:28:22 [2045738] IO: Failed to read packet header<br/>07/28/21 11:28:22 [2045738] SetEffectiveOwner(lcgadmin) failed with errno=110: Connection timed out.<br/>07/28/21 11:28:22 [2045738] Failed to connect to schedd! Will retry</pre><br/>
</body>
</html>
