<!DOCTYPE html>
<html>
<head>
<title>Mon Jan 4, 2021 : #software (osg)</title>
</head>
<body>
<h3>Mon Jan 4, 2021 : #software (osg)</h3>
<span style="color: #99a949"><span style="font-size: small">(12:10:00)</span> <b>dwd:</b></span> It looks like slack is back in action<br/>
<span style="color: #9d8eee"><span style="font-size: small">(13:04:02)</span> <b>cat:</b></span> Indeed, although it is still quite slow for me at times.<br/>
<span style="color: #a63024"><span style="font-size: small">(16:14:19)</span> <b>efajardo:</b></span> <b>@here</b> folks do you know what I am doing wrong that I cannot launch mkdocs for the osg software docs<br/>
<span style="color: #a63024"><span style="font-size: small">(16:14:22)</span> <b>efajardo:</b></span> <pre>mkdocs serve -a 169.228.130.123:8000<br/>INFO    -  Building documentation... <br/>WARNING -  Config value: 'nav'. Warning: Unrecognised configuration name: nav <br/>INFO    -  Cleaning site directory <br/>Traceback (most recent call last):<br/>  File "/usr/bin/mkdocs", line 11, in &lt;module&gt;<br/>    sys.exit(cli())<br/>  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__<br/>    return self.main(*args, **kwargs)<br/>  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main<br/>    rv = self.invoke(ctx)<br/>  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke<br/>    return _process_result(sub_ctx.command.invoke(sub_ctx))<br/>  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke<br/>    return ctx.invoke(self.callback, **ctx.params)<br/>  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke<br/>    return callback(*args, **kwargs)<br/>  File "/usr/lib/python2.7/site-packages/mkdocs/__main__.py", line 127, in serve_command<br/>    livereload=livereload<br/>  File "/usr/lib/python2.7/site-packages/mkdocs/commands/serve.py", line 117, in serve<br/>    config = builder()<br/>  File "/usr/lib/python2.7/site-packages/mkdocs/commands/serve.py", line 112, in builder<br/>    build(config, live_server=live_server, dirty=dirty)<br/>  File "/usr/lib/python2.7/site-packages/mkdocs/commands/build.py", line 282, in build<br/>    build_pages(config, dirty=dirty)<br/>  File "/usr/lib/python2.7/site-packages/mkdocs/commands/build.py", line 227, in build_pages<br/>    build_error_template(template, env, config, site_navigation)<br/>  File "/usr/lib/python2.7/site-packages/mkdocs/commands/build.py", line 115, in build_error_template<br/>    build_template(template, env, config, site_navigation)<br/>  File "/usr/lib/python2.7/site-packages/mkdocs/commands/build.py", line 88, in build_template<br/>    output_content = template.render(context)<br/>  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render<br/>    return self.environment.handle_exception(exc_info, True)<br/>  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception<br/>    reraise(exc_type, exc_value, tb)<br/>  File "/home/efajardo/docs/osgthedocs/partials/footer.html", line 10, in &lt;module&gt;<br/>    &lt;a href="{{ page.previous_page.url | url }}" class="md-footer-nav__link md-footer-nav__link--prev" rel="prev"&gt;<br/>jinja2.exceptions.TemplateAssertionError: no filter named 'url'</pre><br/>
<span style="color: #a63024"><span style="font-size: small">(16:16:40)</span> <b>paschos:</b></span> is it in GitHub Actions ?<br/>
<span style="color: #43761b"><span style="font-size: small">(16:16:51)</span> <b>blin:</b></span> we deploy/preview via docker now: <a href="https://opensciencegrid.org/technology/documentation/writing-documentation/#previewing-the-pages">https://opensciencegrid.org/technology/documentation/writing-documentation/#previewing-the-pages</a><br/>
<span style="color: #a63024"><span style="font-size: small">(16:20:33)</span> <b>efajardo:</b></span> ahh<br/>
<span style="color: #a63024"><span style="font-size: small">(16:20:36)</span> <b>efajardo:</b></span> I did not know what<br/>
</body>
</html>
