<!DOCTYPE html>
<html>
<head>
<title>Wed Jan 18, 2017 : #xcache (osg)</title>
</head>
<body>
<h3>Wed Jan 18, 2017 : #xcache (osg)</h3>
<span style="color: #e7392d"><span style="font-size: small">(13:53:33)</span> <b>bala:</b></span> @dweitzel  published v4.1.1 and made it as default.<br/>
<span style="color: #235e5b"><span style="font-size: small">(13:54:33)</span> <b>dweitzel:</b></span> oh, I thought you did that a bit ago.<br/>
<span style="color: #235e5b"><span style="font-size: small">(13:54:34)</span> <b>dweitzel:</b></span> ok.<br/>
<span style="color: #235e5b"><span style="font-size: small">(13:55:03)</span> <b>dweitzel:</b></span> no worries, sounds good.  Thanks!<br/>
<span style="color: #674b1b"><span style="font-size: small">(15:18:12)</span> <b>rynge:</b></span> Weird stashcp error:<br/>
<span style="color: #674b1b"><span style="font-size: small">(15:18:14)</span> <b>rynge:</b></span> 2017-01-18 08:12:39,064    INFO:  /cvmfs/oasis.opensciencegrid.org/osg/modules/stashcp/4.1.0/bin/stashcp 'user/ldunwoo/public/kinc-1478971524/00/00/Hsapiens-9606-20161025-1793-Quantile-All_Random_Range_Over_0.1-CufflinksHisat-v1.tar.gz' '/var/lib/condor/execute/dir_1943/glide_Gt0S75/execute/dir_44642/pegasus.YIjKNO'<br/>2017-01-18 08:39:48,737    INFO:  WARNING:root:DEPRECIATED: The source path does not begin with a '/', but it is required.  This functionality will be removed in an upcoming release<br/>[FATAL] Connection error<br/>Traceback (most recent call last):<br/>  File "/cvmfs/oasis.opensciencegrid.org/osg/modules/stashcp/4.1.0/bin/stashcp", line 329, in &lt;module&gt;<br/>    main()<br/>  File "/cvmfs/oasis.opensciencegrid.org/osg/modules/stashcp/4.1.0/bin/stashcp", line 323, in main<br/>    doStashCpSingle(sourceFile=source, destination=destination, cache=cache, debug=args.debug)<br/>  File "/cvmfs/oasis.opensciencegrid.org/osg/modules/stashcp/4.1.0/bin/stashcp", line 29, in doStashCpSingle<br/>    fileSize = int(re.findall(r"Size:   \d+", xrdfs)[0].split(":   ")[1])<br/>IndexError: list index out of range<br/>
<span style="color: #674b1b"><span style="font-size: small">(15:19:45)</span> <b>rynge:</b></span> Seems like it didn't retry<br/>
<span style="color: #235e5b"><span style="font-size: small">(15:20:23)</span> <b>dweitzel:</b></span> Ah, that usually happens if the falie doesn't exist.<br/>
<span style="color: #235e5b"><span style="font-size: small">(15:20:25)</span> <b>dweitzel:</b></span> file*<br/>
<span style="color: #674b1b"><span style="font-size: small">(15:20:36)</span> <b>rynge:</b></span> Probably the connection error<br/>
<span style="color: #235e5b"><span style="font-size: small">(15:20:49)</span> <b>dweitzel:</b></span> Yup, can't connect to stash.<br/>
<span style="color: #674b1b"><span style="font-size: small">(15:20:49)</span> <b>rynge:</b></span> File exists - same command works on for example the login hosts<br/>
<span style="color: #674b1b"><span style="font-size: small">(15:20:59)</span> <b>rynge:</b></span> Ah I see<br/>
<span style="color: #235e5b"><span style="font-size: small">(15:21:00)</span> <b>dweitzel:</b></span> yeah, connection error is the error.<br/>
<span style="color: #674b1b"><span style="font-size: small">(15:21:10)</span> <b>rynge:</b></span> So it went all the way back to origin, and that is where the connection failed?<br/>
<span style="color: #235e5b"><span style="font-size: small">(15:21:13)</span> <b>dweitzel:</b></span> 5000 edge case errors.<br/>
<span style="color: #235e5b"><span style="font-size: small">(15:21:23)</span> <b>dweitzel:</b></span> yeah, it gets the size of the file from the origin.<br/>
<span style="color: #674b1b"><span style="font-size: small">(15:21:30)</span> <b>rynge:</b></span> Ok<br/>
</body>
</html>
